apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: app
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "Root123!"
  MARIADB_DATABASE: "mainappdb"
  MARIADB_USER: "mainapp"
  MARIADB_PASSWORD: "MainApp123!"
